Added npm prep
blackbaud/skyux-builder-plugin-code-block pull request #2
Opened 2017-05-02 18:42 UTC by Blackbaud-SteveBrush

2017-05-02 19:42 UTC, Blackbaud-SteveBrush commented on .travis.yml
> +  - "sh -e /etc/init.d/xvfb start"
@Blackbaud-BobbyEarl Do I still need this bit, for headless browser support?

2017-05-02 19:44 UTC, Blackbaud-BobbyEarl commented on .travis.yml
> +  - "sh -e /etc/init.d/xvfb start"
Safe to remove these lines.

2017-05-02 20:06 UTC, Blackbaud-SteveBrush commented on .travis.yml
> +  - "sh -e /etc/init.d/xvfb start"
Done.

2017-05-02 20:24 UTC, Blackbaud-BobbyEarl requested changes

2017-05-02 20:24 UTC, Blackbaud-BobbyEarl commented on .travis.yml
> +  firefox: "52.0.2"
You can also remove this.

2017-05-02 20:24 UTC, Blackbaud-BobbyEarl commented on scripts/prepare-package.js
> +  fs.copySync(path.join(rootPath, 'src/code-block.js'), path.join(distPath, 'index.js'));
I would change this to `path.join(rootPath, 'src', 'code-block.js')`.

2017-05-02 20:24 UTC, Blackbaud-BobbyEarl commented on scripts/prepare-package.js
> +    fs.mkdirSync('dist');
I would change `'dist'` to use `distPath`.

2017-05-03 13:16 UTC, Blackbaud-SteveBrush commented
@Blackbaud-BobbyEarl Ready for another look, thanks!

2017-05-03 13:36 UTC, Blackbaud-BobbyEarl approved these changes

2017-05-03 14:29 UTC, merged